"""Pydantic models for procedure transformation pipeline."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

# =============================================================================
# Core TTP Models - Base (used by Translate/Validate)
# =============================================================================


class ActionStepBase(BaseModel):
    """Step as output by translate node - no tracking fields."""

    tactic: str = Field(description="MITRE ATT&CK tactic (e.g., 'Initial Access', 'Discovery')")
    technique_id: str = Field(description="MITRE ATT&CK technique ID (e.g., 'T1021.001')")
    technique_name: str = Field(
        description="MITRE ATT&CK technique name (e.g., 'Remote Desktop Protocol')"
    )
    os: str = Field(description="Operating system (Windows, Linux, macOS)")
    command: str = Field(description="The command to execute")
    description: str = Field(description="What this step accomplishes")
    # FRE: Start of new code
    required_privilege: str = Field(
        description="Required privilege level (e.g., 'user', 'elevated')"
    )
    dependencies_constraints: str = Field(
        description="Any dependencies or OS-specific constraints for this step (e.g., 'Requires PowerShell 5.0 or later')"
    )
    telemetry_expected: str = Field(
        description="Expected telemetry generated by this step including telemetry class, platform, sensor requirement, eventID, and any other relevant details "
        "(e.g., 'Process creation event with command line arguments, requires Sysmon with ProcessCreate enabled')"
    )
    # FRE: End of new code


class TTPOutputBase(BaseModel):
    """Output from translate node - flat action sequence."""

    action_sequence: list[ActionStepBase]


# =============================================================================
# Core TTP Models - Full (used by Convert/Refine/Output)
# =============================================================================


class ActionStep(BaseModel):
    """Step with full tracking fields - output by convert node."""

    step_id: int = Field(description="Sequential ID in the action sequence")
    original_step_id: int | None = Field(
        default=None, description="Reference to original step if split (null for 1:1 conversions)"
    )
    tactic: str = Field(description="MITRE ATT&CK tactic")
    technique_id: str = Field(description="MITRE ATT&CK technique ID")
    technique_name: str = Field(description="MITRE ATT&CK technique name")
    os: str = Field(description="Operating system")
    host: str = Field(
        description="Target host where command executes (e.g., 'attacker-kali', '10.20.10.16')"
    )
    command: str = Field(description="The command to execute")
    description: str = Field(description="What this step accomplishes")
    # FRE: Start of new code
    required_privilege: str = Field(
        description="Required privilege level (e.g., 'user', 'elevated')"
    )
    dependencies_constraints: str = Field(
        description="Any dependencies or OS-specific constraints for this step (e.g., 'Requires PowerShell 5.0 or later')"
    )
    telemetry_expected: str = Field(
        description="Expected telemetry generated by this step including telemetry class, platform, sensor requirement, eventID, and any other relevant details "
        "(e.g., 'Process creation event with command line arguments, requires Sysmon with ProcessCreate enabled')"
    )
    # FRE: End of new code


class TTPOutput(BaseModel):
    """Complete output structure with tracking fields."""

    action_sequence: list[ActionStep]


# =============================================================================
# Stage 2: Validation Models
# =============================================================================


class ValidationIssueType(str, Enum):
    MISSING_STEP = "missing_step"
    INCORRECT_TTP = "incorrect_ttp"
    INACCURATE_PURPOSE = "inaccurate_purpose"
    COMMAND_MISMATCH = "command_mismatch"
    MISC = "miscellaneous"


class ValidationIssue(BaseModel):
    """A single validation issue found during verification."""

    issue_type: ValidationIssueType
    location: str = Field(description="JSON path to the issue location")
    original: str | None = Field(default=None, description="Original value (null if missing)")
    corrected: str = Field(description="Corrected value")
    justification: str = Field(description="Reason for the correction")


class ValidationResult(BaseModel):
    """Result of validating a TTPOutputBase."""

    is_valid: bool = Field(description="True if no issues found")
    validated_output: TTPOutputBase = Field(description="Corrected TTPOutputBase structure")
    validation_issues: list[ValidationIssue] = Field(default_factory=list)


# =============================================================================
# Stage 3: OS Conversion Models
# =============================================================================


class ConversionType(str, Enum):
    DIRECT = "direct"  # 1:1 command mapping
    EQUIVALENT = "equivalent"  # Different command, same result
    APPROXIMATION = "approximation"  # Similar but not identical behavior
    UNSUPPORTED = "unsupported"  # No equivalent on target OS


class ConversionNote(BaseModel):
    """Documentation for a single action conversion."""

    original_action: str = Field(description="Source OS command")
    converted_action: str | None = Field(
        default=None, description="Target OS command (null if unsupported)"
    )
    conversion_type: ConversionType
    notes: str = Field(description="Explanation of conversion choices")


class ConversionResult(BaseModel):
    """Result of OS conversion process."""

    converted_output: TTPOutput = Field(description="TTPOutput for target OS")
    conversion_notes: list[ConversionNote] = Field(default_factory=list)


# =============================================================================
# Stage 3.5: Environment Extraction Models
# =============================================================================


class EnvironmentHost(BaseModel):
    """A host in the adversary's execution environment."""

    identifier: str = Field(
        description="Host identifier (hostname, IP, or descriptive name like 'attacker-kali')"
    )
    os: str = Field(description="Operating system (windows, linux, macos)")
    role: str | None = Field(
        default=None, description="Role in the attack (e.g., 'attacker', 'pivot', 'target')"
    )
    # FRE: Start of new code
    privileges: str | None = Field(
        default=None, description="Adversary privileges on the host (e.g., 'user', 'admin', 'root')"
    )
    # FRE: End of new code


class EnvironmentMap(BaseModel):
    """Map of hosts the adversary executes commands on."""

    hosts: list[EnvironmentHost] = Field(
        description="List of execution hosts identified in the procedure"
    )


class ConvertedEnvironment(BaseModel):
    """Result of environment conversion - hosts with updated OS values."""

    converted_hosts: list[EnvironmentHost] = Field(
        description="List of hosts after OS conversion applied"
    )


# =============================================================================
# Stage 4: Refinement Models
# =============================================================================


class RefinementType(str, Enum):
    SYNTAX_FIX = "syntax_fix"
    PATH_CORRECTION = "path_correction"
    PERMISSION_NOTE = "permission_note"
    DEPENDENCY_ADD = "dependency_add"
    COMMAND_UPDATE = "command_update"


class Severity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class RefinementAction(BaseModel):
    """A single refinement made during validation."""

    action_index: int = Field(description="Index in action_sequence")
    refinement_type: RefinementType
    before: str
    after: str
    reason: str


class ValidationWarning(BaseModel):
    """Warning or issue found during validation."""

    severity: Severity
    message: str


class RefinementResult(BaseModel):
    """Result of conversion validation pass."""

    is_valid: bool
    refined_output: TTPOutput
    refinement_actions: list[RefinementAction] = Field(default_factory=list)
    warnings: list[ValidationWarning] = Field(default_factory=list)


# =============================================================================
# Stage 5: Output Models
# =============================================================================


class ProcedureMetadata(BaseModel):
    """Metadata for the generated procedure."""

    source_file: str
    source_os: str
    target_os: str
    generated_at: datetime
    model: str
    total_duration_ms: int = Field(default=0, description="Total duration in milliseconds")


class ValidationSummary(BaseModel):
    """Summary of validation across all stages."""

    initial_validation_issues: int
    conversion_notes_count: int
    refinements_applied: int
    warnings: list[str] = Field(default_factory=list)


class FinalOutput(BaseModel):
    """Complete output structure for variant test."""

    metadata: ProcedureMetadata
    procedure: TTPOutput
    validation_summary: ValidationSummary


# =============================================================================
# Workflow State Models
# =============================================================================


class StepMetadata(BaseModel):
    """Metadata for a single pipeline step."""

    step_name: str
    model: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    duration_ms: int
    timestamp: datetime = Field(default_factory=datetime.now)


class OperatingSystem(str, Enum):
    WINDOWS = "windows"
    LINUX = "linux"
    MACOS = "macos"


# =============================================================================
# D3FEND Enrichment Models
# =============================================================================


class StepObservables(BaseModel):
    """D3FEND observables extracted for a single action step."""

    step_id: int = Field(description="The step ID this enrichment applies to")
    d3fend_observables: list[str] = Field(
        description="All D3FEND artifact classes relevant to this technique (theoretical)"
    )
    execution_observables: list[str] = Field(
        description="D3FEND artifacts actually produced by this specific command execution"
    )
    telemetry_classes: list[str] = Field(
        description="Simplified telemetry categories (process, file, network, etc.)"
    )
    execution_level: str = Field(
        description="Execution privilege level: 'elevated' or 'non-elevated'"
    )


class EnrichedActionStep(BaseModel):
    """ActionStep enriched with D3FEND observable information."""

    step_id: int = Field(description="Sequential ID in the action sequence")
    original_step_id: int | None = Field(
        default=None,
        description="Reference to original step if split (null for 1:1 conversions)",
    )
    tactic: str = Field(description="MITRE ATT&CK tactic")
    technique_id: str = Field(description="MITRE ATT&CK technique ID")
    technique_name: str = Field(description="MITRE ATT&CK technique name")
    os: str = Field(description="Operating system")
    host: str = Field(description="Target host where command executes")
    command: str = Field(description="The command to execute")
    description: str = Field(description="What this step accomplishes")
    d3fend_observables: list[str] = Field(
        description="All D3FEND artifact classes relevant to this technique"
    )
    execution_observables: list[str] = Field(
        description="D3FEND artifacts actually produced by this specific execution"
    )
    telemetry_classes: list[str] = Field(
        description="Simplified telemetry categories (process, file, network, etc.)"
    )
    execution_level: str = Field(
        description="Execution privilege level: 'elevated' or 'non-elevated'"
    )


class EnrichedTTPOutput(BaseModel):
    """TTPOutput with D3FEND enrichment on each step."""

    action_sequence: list[EnrichedActionStep]


class EnrichmentResult(BaseModel):
    """Result of the enrichment process."""

    enriched_output: EnrichedTTPOutput = Field(description="Enriched procedure")
    steps_enriched: int = Field(description="Number of steps that were enriched")


class EnrichmentMetadata(BaseModel):
    """Metadata for the enrichment process."""

    source_file: str
    enriched_at: datetime
    model: str
    total_duration_ms: int


class EnrichedFinalOutput(BaseModel):
    """Complete output structure for enrichment workflow."""

    metadata: EnrichmentMetadata
    procedure: EnrichedTTPOutput


# =============================================================================
# Evaluation Models
# =============================================================================


class OSConstructViolation(BaseModel):
    """A single OS construct violation found in a command."""

    step_id: int = Field(description="Step ID where violation was found")
    command: str = Field(description="The command containing the violation")
    violation: str = Field(description="The specific violation found (e.g., 'powershell.exe')")
    source: str = Field(description="Detection source: 'pattern' or 'llm'")


class EvaluationMeasure(BaseModel):
    """A single pass/fail evaluation measure."""

    name: str = Field(description="Name of the measure")
    passed: bool = Field(description="Whether the measure passed")
    detail: str = Field(default="", description="Details if failed, empty if passed")


class EvaluationMetadata(BaseModel):
    """Metadata for the evaluation process."""

    source_file: str
    control_file: str
    source_os: str
    target_os: str
    evaluated_at: datetime
    model: str


class EvaluationResult(BaseModel):
    """Complete evaluation output with pass/fail measures."""

    metadata: EvaluationMetadata
    missing_steps: EvaluationMeasure = Field(
        description="Are any steps in the control missing from the variant?"
    )
    extra_steps: EvaluationMeasure = Field(
        description="Are any new steps present in the variant not in control?"
    )
    os_constructs_valid: EvaluationMeasure = Field(
        description="Does the procedure avoid Windows-only constructs on non-Windows?"
    )
    technique_ids_match: EvaluationMeasure = Field(
        description="Do variant and control map to the same ATT&CK technique IDs (exact match)?"
    )
    parent_technique_ids_match: EvaluationMeasure = Field(
        description="Do variant and control map to the same parent ATT&CK techniques (ignores subtechnique)?"
    )
    telemetry_classes_match: EvaluationMeasure = Field(
        description="Does variant generate the same telemetry classes as control?"
    )
    extra_telemetry_classes: EvaluationMeasure = Field(
        description="Are additional telemetry classes present in variant?"
    )
    telemetry_diversity: EvaluationMeasure = Field(
        description="Does variant have same level of telemetry diversity as control?"
    )
    telemetry_multi_class: EvaluationMeasure = Field(
        description="Does execution generate telemetry in more than one telemetry class?"
    )
    technique_sequence_match: EvaluationMeasure = Field(
        description="Does variant preserve the same ordered sequence of techniques as control?"
    )
    tactic_sequence_match: EvaluationMeasure = Field(
        description="Does variant preserve the same ordered sequence of tactics as control?"
    )
    privilege_progression_match: EvaluationMeasure = Field(
        description="Does variant preserve the same privilege context progression as control?"
    )
    all_pass: bool = Field(description="True if all measures passed")

    def to_csv_row(self) -> dict:
        """Convert to a flat dictionary for CSV output."""

        def sanitize(text: str) -> str:
            """Remove newlines and CRLF from text for CSV compatibility."""
            return text.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")

        return {
            "source_file": self.metadata.source_file,
            "control_file": self.metadata.control_file,
            "source_os": self.metadata.source_os,
            "target_os": self.metadata.target_os,
            "evaluated_at": self.metadata.evaluated_at.isoformat(),
            "model": self.metadata.model,
            "missing_steps_pass": self.missing_steps.passed,
            "missing_steps_detail": sanitize(self.missing_steps.detail),
            "extra_steps_pass": self.extra_steps.passed,
            "extra_steps_detail": sanitize(self.extra_steps.detail),
            "os_constructs_pass": self.os_constructs_valid.passed,
            "os_constructs_detail": sanitize(self.os_constructs_valid.detail),
            "technique_ids_pass": self.technique_ids_match.passed,
            "technique_ids_detail": sanitize(self.technique_ids_match.detail),
            "parent_technique_ids_pass": self.parent_technique_ids_match.passed,
            "parent_technique_ids_detail": sanitize(self.parent_technique_ids_match.detail),
            "telemetry_classes_pass": self.telemetry_classes_match.passed,
            "telemetry_classes_detail": sanitize(self.telemetry_classes_match.detail),
            "extra_telemetry_pass": self.extra_telemetry_classes.passed,
            "extra_telemetry_detail": sanitize(self.extra_telemetry_classes.detail),
            "telemetry_diversity_pass": self.telemetry_diversity.passed,
            "telemetry_diversity_detail": sanitize(self.telemetry_diversity.detail),
            "telemetry_multi_class_pass": self.telemetry_multi_class.passed,
            "telemetry_multi_class_detail": sanitize(self.telemetry_multi_class.detail),
            "technique_sequence_pass": self.technique_sequence_match.passed,
            "technique_sequence_detail": sanitize(self.technique_sequence_match.detail),
            "tactic_sequence_pass": self.tactic_sequence_match.passed,
            "tactic_sequence_detail": sanitize(self.tactic_sequence_match.detail),
            "privilege_progression_pass": self.privilege_progression_match.passed,
            "privilege_progression_detail": sanitize(self.privilege_progression_match.detail),
            "all_pass": self.all_pass,
        }


class FullPipelineOutput(BaseModel):
    """Complete output from full pipeline with enriched procedure."""

    metadata: ProcedureMetadata
    environment: dict = Field(description="Original and converted host environments")
    procedure: EnrichedTTPOutput = Field(description="Enriched procedure with D3FEND observables")
    intermediate_output: dict = Field(description="Validation and conversion notes")
    evaluation: EvaluationResult | None = Field(
        default=None, description="EvaluationResult if control file provided, else null"
    )
